# coding: utf-8
#
# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.

__all__ = [
    "TrackingResponseForGetTrackingsDataPagination",
    "TrackingResponseForGetTrackingsData",
    "TrackingResponseForGetTrackings",
    "MetaType",
    "Meta",
    "TrackingCourierEstimatedDeliveryDate",
    "TrackingShipmentWeight",
    "TrackingAftershipEstimatedDeliveryDate",
    "TrackingCustomEstimatedDeliveryDateType",
    "TrackingCustomEstimatedDeliveryDate",
    "TrackingFirstEstimatedDeliveryType",
    "TrackingFirstEstimatedDeliverySource",
    "TrackingFirstEstimatedDelivery",
    "TrackingLatestEstimatedDeliveryType",
    "TrackingLatestEstimatedDeliverySource",
    "TrackingLatestEstimatedDelivery",
    "TrackingCarbonEmissions",
    "TrackingSignatureRequirement",
    "TrackingFirstMile",
    "TrackingLastMileSource",
    "TrackingLastMile",
    "TrackingCustomers",
    "Tracking",
    "Tag",
    "CheckpointCoordinate",
    "CheckpointEventsReason",
    "CheckpointEvents",
    "CheckpointSource",
    "Checkpoint",
    "TrackingResponse",
    "CourierResponseData",
    "CourierResponse",
    "CourierCredentials",
    "Courier",
    "AdditionalFields",
    "CredentialField",
    "CourierConnectionResponseForGetCourierConnectionsDataPagination",
    "CourierConnectionResponseForGetCourierConnectionsData",
    "CourierConnectionResponseForGetCourierConnections",
    "CourierConnection",
    "EstimatedDeliveryDateRequestOriginAddress",
    "EstimatedDeliveryDateRequestDestinationAddress",
    "EstimatedDeliveryDateRequestWeight",
    "EstimatedDeliveryDateRequestEstimatedPickupOrderProcessingTime",
    "EstimatedDeliveryDateRequestEstimatedPickup",
    "EstimatedDeliveryDateRequest",
    "EstimatedDeliveryDateResponseOriginAddress",
    "EstimatedDeliveryDateResponseDestinationAddress",
    "EstimatedDeliveryDateResponseWeight",
    "EstimatedDeliveryDateResponseEstimatedPickupOrderProcessingTime",
    "EstimatedDeliveryDateResponseEstimatedPickup",
    "EstimatedDeliveryDateResponse",
    "GetTrackingsResponseData",
    "GetTrackingsResponseDataPagination",
    "GetTrackingsResponse",
    "CreateTrackingRequestDeliveryType",
    "CreateTrackingRequestLastMile",
    "CreateTrackingRequestCustomers",
    "CreateTrackingRequest",
    "CreateTrackingResponse",
    "GetTrackingByIdResponse",
    "UpdateTrackingByIdRequestDeliveryType",
    "UpdateTrackingByIdRequestCustomers",
    "UpdateTrackingByIdRequest",
    "UpdateTrackingByIdResponse",
    "DeleteTrackingByIdResponse",
    "RetrackTrackingByIdResponse",
    "MarkTrackingCompletedByIdRequestReason",
    "MarkTrackingCompletedByIdRequest",
    "MarkTrackingCompletedByIdResponse",
    "GetCouriersResponseData",
    "GetCouriersResponse",
    "DetectCourierRequest",
    "DetectCourierResponseData",
    "DetectCourierResponse",
    "GetCourierConnectionsResponseData",
    "GetCourierConnectionsResponseDataPagination",
    "GetCourierConnectionsResponse",
    "PostCourierConnectionsRequest",
    "PostCourierConnectionsResponse",
    "GetCourierConnectionsByIdResponse",
    "PutCourierConnectionsByIdRequest",
    "PutCourierConnectionsByIdResponse",
    "DeleteCourierConnectionsByIdResponse",
    "PredictResponse",
    "PredictBatchRequest",
    "PredictBatchResponseData",
    "PredictBatchResponse",
]

from .tracking_response_for_get_trackings_data_pagination import (
    TrackingResponseForGetTrackingsDataPagination,
)
from .tracking_response_for_get_trackings_data import TrackingResponseForGetTrackingsData
from .tracking_response_for_get_trackings import TrackingResponseForGetTrackings
from .meta_type import MetaType
from .meta import Meta
from .tracking_courier_estimated_delivery_date import TrackingCourierEstimatedDeliveryDate
from .tracking_shipment_weight import TrackingShipmentWeight
from .tracking_aftership_estimated_delivery_date import TrackingAftershipEstimatedDeliveryDate
from .tracking_custom_estimated_delivery_date_type import TrackingCustomEstimatedDeliveryDateType
from .tracking_custom_estimated_delivery_date import TrackingCustomEstimatedDeliveryDate
from .tracking_first_estimated_delivery_type import TrackingFirstEstimatedDeliveryType
from .tracking_first_estimated_delivery_source import TrackingFirstEstimatedDeliverySource
from .tracking_first_estimated_delivery import TrackingFirstEstimatedDelivery
from .tracking_latest_estimated_delivery_type import TrackingLatestEstimatedDeliveryType
from .tracking_latest_estimated_delivery_source import TrackingLatestEstimatedDeliverySource
from .tracking_latest_estimated_delivery import TrackingLatestEstimatedDelivery
from .tracking_carbon_emissions import TrackingCarbonEmissions
from .tracking_signature_requirement import TrackingSignatureRequirement
from .tracking_first_mile import TrackingFirstMile
from .tracking_last_mile_source import TrackingLastMileSource
from .tracking_last_mile import TrackingLastMile
from .tracking_customers import TrackingCustomers
from .tracking import Tracking
from .tag import Tag
from .checkpoint_coordinate import CheckpointCoordinate
from .checkpoint_events_reason import CheckpointEventsReason
from .checkpoint_events import CheckpointEvents
from .checkpoint_source import CheckpointSource
from .checkpoint import Checkpoint
from .tracking_response import TrackingResponse
from .courier_response_data import CourierResponseData
from .courier_response import CourierResponse
from .courier_credentials import CourierCredentials
from .courier import Courier
from .additional_fields import AdditionalFields
from .credential_field import CredentialField
from .courier_connection_response_for_get_courier_connections_data_pagination import (
    CourierConnectionResponseForGetCourierConnectionsDataPagination,
)
from .courier_connection_response_for_get_courier_connections_data import (
    CourierConnectionResponseForGetCourierConnectionsData,
)
from .courier_connection_response_for_get_courier_connections import (
    CourierConnectionResponseForGetCourierConnections,
)
from .courier_connection import CourierConnection
from .estimated_delivery_date_request_origin_address import (
    EstimatedDeliveryDateRequestOriginAddress,
)
from .estimated_delivery_date_request_destination_address import (
    EstimatedDeliveryDateRequestDestinationAddress,
)
from .estimated_delivery_date_request_weight import EstimatedDeliveryDateRequestWeight
from .estimated_delivery_date_request_estimated_pickup_order_processing_time import (
    EstimatedDeliveryDateRequestEstimatedPickupOrderProcessingTime,
)
from .estimated_delivery_date_request_estimated_pickup import (
    EstimatedDeliveryDateRequestEstimatedPickup,
)
from .estimated_delivery_date_request import EstimatedDeliveryDateRequest
from .estimated_delivery_date_response_origin_address import (
    EstimatedDeliveryDateResponseOriginAddress,
)
from .estimated_delivery_date_response_destination_address import (
    EstimatedDeliveryDateResponseDestinationAddress,
)
from .estimated_delivery_date_response_weight import EstimatedDeliveryDateResponseWeight
from .estimated_delivery_date_response_estimated_pickup_order_processing_time import (
    EstimatedDeliveryDateResponseEstimatedPickupOrderProcessingTime,
)
from .estimated_delivery_date_response_estimated_pickup import (
    EstimatedDeliveryDateResponseEstimatedPickup,
)
from .estimated_delivery_date_response import EstimatedDeliveryDateResponse
from .get_trackings_response_data import GetTrackingsResponseData
from .get_trackings_response_data_pagination import GetTrackingsResponseDataPagination
from .get_trackings_response import GetTrackingsResponse
from .create_tracking_request_delivery_type import CreateTrackingRequestDeliveryType
from .create_tracking_request_last_mile import CreateTrackingRequestLastMile
from .create_tracking_request_customers import CreateTrackingRequestCustomers
from .create_tracking_request import CreateTrackingRequest
from .create_tracking_response import CreateTrackingResponse
from .get_tracking_by_id_response import GetTrackingByIdResponse
from .update_tracking_by_id_request_delivery_type import UpdateTrackingByIdRequestDeliveryType
from .update_tracking_by_id_request_customers import UpdateTrackingByIdRequestCustomers
from .update_tracking_by_id_request import UpdateTrackingByIdRequest
from .update_tracking_by_id_response import UpdateTrackingByIdResponse
from .delete_tracking_by_id_response import DeleteTrackingByIdResponse
from .retrack_tracking_by_id_response import RetrackTrackingByIdResponse
from .mark_tracking_completed_by_id_request_reason import MarkTrackingCompletedByIdRequestReason
from .mark_tracking_completed_by_id_request import MarkTrackingCompletedByIdRequest
from .mark_tracking_completed_by_id_response import MarkTrackingCompletedByIdResponse
from .get_couriers_response_data import GetCouriersResponseData
from .get_couriers_response import GetCouriersResponse
from .detect_courier_request import DetectCourierRequest
from .detect_courier_response_data import DetectCourierResponseData
from .detect_courier_response import DetectCourierResponse
from .get_courier_connections_response_data import GetCourierConnectionsResponseData
from .get_courier_connections_response_data_pagination import (
    GetCourierConnectionsResponseDataPagination,
)
from .get_courier_connections_response import GetCourierConnectionsResponse
from .post_courier_connections_request import PostCourierConnectionsRequest
from .post_courier_connections_response import PostCourierConnectionsResponse
from .get_courier_connections_by_id_response import GetCourierConnectionsByIdResponse
from .put_courier_connections_by_id_request import PutCourierConnectionsByIdRequest
from .put_courier_connections_by_id_response import PutCourierConnectionsByIdResponse
from .delete_courier_connections_by_id_response import DeleteCourierConnectionsByIdResponse
from .predict_response import PredictResponse
from .predict_batch_request import PredictBatchRequest
from .predict_batch_response_data import PredictBatchResponseData
from .predict_batch_response import PredictBatchResponse
