# coding: utf-8
#
# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.

from enum import Enum, unique


@unique
class AdditionalFields(Enum):
    """
    All available additional fields

    allowed enum values
    """

    TRACKING_ACCOUNT_NUMBER = "tracking_account_number"
    DESTINATION_POSTAL_CODE = "destination_postal_code"
    DESTINATION_STATE = "destination_state"
    TRACKING_KEY = "tracking_key"
    ORIGIN_COUNTRY_REGION = "origin_country_region"
    DESTINATION_COUNTRY_REGION = "destination_country_region"
    TRACKING_SHIP_DATE = "tracking_ship_date"
