# coding: utf-8
#
# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.

from enum import Enum, unique


@unique
class CheckpointSource(Enum):
    """
    The source of the checkpoint, which can either be from the carrier or when the user marks the tracking as completed.

    allowed enum values
    """

    CARRIER = "carrier"
    USER = "user"
