# coding: utf-8
#
# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.

from enum import Enum, unique


@unique
class CreateTrackingRequestDeliveryType(Enum):
    """
    Shipment delivery type- pickup_at_store- pickup_at_courier- door_to_door

    allowed enum values
    """

    PICKUP_AT_STORE = "pickup_at_store"
    DOOR_TO_DOOR = "door_to_door"
    PICKUP_AT_COURIER = "pickup_at_courier"
