# coding: utf-8
#
# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.

from __future__ import annotations
import pprint

from pydantic import BaseModel
from typing import Any, Dict, Optional
from typing_extensions import Self

from tracking.models.origin_address_estimated_delivery_date_response import (
    OriginAddressEstimatedDeliveryDateResponse,
)
from tracking.models.destination_address_estimated_delivery_date_response import (
    DestinationAddressEstimatedDeliveryDateResponse,
)
from tracking.models.weight_estimated_delivery_date_response import (
    WeightEstimatedDeliveryDateResponse,
)
from tracking.models.estimated_pickup_estimated_delivery_date_response import (
    EstimatedPickupEstimatedDeliveryDateResponse,
)


class EstimatedDeliveryDateResponse(BaseModel):
    """
    EstimatedDeliveryDateResponse
    """  # noqa: E501

    id: Optional[str] = None
    slug: Optional[str] = None
    service_type_name: Optional[str] = None
    origin_address: Optional[OriginAddressEstimatedDeliveryDateResponse] = None
    destination_address: Optional[DestinationAddressEstimatedDeliveryDateResponse] = None
    weight: Optional[WeightEstimatedDeliveryDateResponse] = None
    package_count: Optional[int] = None
    pickup_time: Optional[str] = None
    estimated_pickup: Optional[EstimatedPickupEstimatedDeliveryDateResponse] = None
    estimated_delivery_date: Optional[str] = None
    confidence_code: Optional[float] = None
    estimated_delivery_date_min: Optional[str] = None
    estimated_delivery_date_max: Optional[str] = None

    def to_str(self, **kwargs) -> str:
        return pprint.pformat(self.model_dump(**kwargs))

    def to_json(self, **kwargs) -> str:
        return self.model_dump_json(**kwargs)

    def to_dict(self, **kwargs) -> Dict[str, Any]:
        return self.model_dump(**kwargs)

    @classmethod
    def from_json(cls, json_str: str, **kwargs) -> Optional[Self]:
        return cls.model_validate_json(json_str, **kwargs)

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]], **kwargs) -> Optional[Self]:
        return cls.model_validate(obj, **kwargs) if isinstance(obj, Dict) else None
