# coding: utf-8
#
# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.

from enum import Enum, unique


@unique
class MetaType(Enum):
    """
    error type, only exist if the response status is not 2xx

    allowed enum values
    """

    BAD_REQUEST = "BadRequest"
    UNAUTHORIZED = "Unauthorized"
    FORBIDDEN = "Forbidden"
    NOT_FOUND = "NotFound"
    TOO_MANY_REQUESTS = "TooManyRequests"
    INTERNAL_ERROR = "InternalError"
