# coding: utf-8
#
# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.

from enum import Enum, unique


@unique
class SlugGroupV1(Enum):
    """
    Slug group is a group of slugs which belong to same courier. For example, when you inpit "fedex-group" as slug_group, AfterShip will detect the tracking with "fedex-uk", "fedex-fims", and other slugs which belong to "fedex". It cannot be used with slug at the same time. (

    allowed enum values
    """

    AMAZON_GROUP = "amazon-group"
    FEDEX_GROUP = "fedex-group"
    TOLL_GROUP = "toll-group"
    TAQBIN_GROUP = "taqbin-group"
    TNT_GROUP = "tnt-group"
    CJ_GROUP = "cj-group"
    HERMES_GROUP = "hermes-group"
    DPD_GROUP = "dpd-group"
    GLS_GROUP = "gls-group"
    DHL_GROUP = "dhl-group"
    FASTWAY_GROUP = "fastway-group"
    ASENDIA_GROUP = "asendia-group"
