# coding: utf-8
#
# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.

from enum import Enum, unique


@unique
class Tag(Enum):
    """
    Current status of tracking. (

    allowed enum values
    """

    PENDING = "Pending"
    INFO_RECEIVED = "InfoReceived"
    IN_TRANSIT = "InTransit"
    OUT_FOR_DELIVERY = "OutForDelivery"
    ATTEMPT_FAIL = "AttemptFail"
    DELIVERED = "Delivered"
    AVAILABLE_FOR_PICKUP = "AvailableForPickup"
    EXCEPTION = "Exception"
    EXPIRED = "Expired"
