# coding: utf-8
#
# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.

from enum import Enum, unique


@unique
class TagV1(Enum):
    """
    Current status of tracking. (

    allowed enum values
    """

    PENDING = "Pending"
    INFORECEIVED = "InfoReceived"
    INTRANSIT = "InTransit"
    OUTFORDELIVERY = "OutForDelivery"
    ATTEMPTFAIL = "AttemptFail"
    DELIVERED = "Delivered"
    AVAILABLEFORPICKUP = "AvailableForPickup"
    EXCEPTION = "Exception"
    EXPIRED = "Expired"
