# coding: utf-8
#
# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.

from enum import Enum, unique


@unique
class TrackingFirstEstimatedDeliveryType(Enum):
    """
    The format of the EDD. Either a single date or a date range.

    allowed enum values
    """

    RANGE = "range"
    SPECIFIC = "specific"
