# coding: utf-8
#
# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.

from enum import Enum, unique


@unique
class TrackingFirstEstimatedDeliverySource(Enum):
    """
    The source of the EDD. Either the carrier, AfterShip AI, or based on your custom EDD settings.

    allowed enum values
    """

    CARRIER_EDD = "Carrier EDD"
    AFTER_SHIP_EDD = "AfterShip EDD"
    CUSTOM_EDD = "Custom EDD"
    ORDER_EDD = "Order EDD"
