# coding: utf-8
#
# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.

from enum import Enum, unique


@unique
class TrackingMultiPieceInfoPiecesType(Enum):
    """
    Type of the piece within the MPS: `master` or `child`.

    allowed enum values
    """
    MASTER = "master"
    CHILD = "child"
