# coding: utf-8
#
# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.

from __future__ import annotations
import pprint

from pydantic import BaseModel
from typing import Any, Dict, List, Optional
from typing_extensions import Self

from tracking.models.custom_fields_tracking_update_tracking_by_slug_tracking_number_request import (
    CustomFieldsTrackingUpdateTrackingBySlugTrackingNumberRequest,
)


class TrackingUpdateTrackingBySlugTrackingNumberRequest(BaseModel):
    """
    TrackingUpdateTrackingBySlugTrackingNumberRequest
    """  # noqa: E501

    smses: Optional[List[str]] = None
    emails: Optional[List[str]] = None
    title: Optional[str] = None
    customer_name: Optional[str] = None
    order_id: Optional[str] = None
    order_id_path: Optional[str] = None
    custom_fields: Optional[CustomFieldsTrackingUpdateTrackingBySlugTrackingNumberRequest] = None
    note: Optional[str] = None
    language: Optional[str] = None
    order_promised_delivery_date: Optional[str] = None
    delivery_type: Optional[str] = None
    pickup_location: Optional[str] = None
    pickup_note: Optional[str] = None
    slug: Optional[str] = None
    tracking_account_number: Optional[str] = None
    tracking_origin_country: Optional[str] = None
    tracking_destination_country: Optional[str] = None
    tracking_key: Optional[str] = None
    tracking_postal_code: Optional[str] = None
    tracking_ship_date: Optional[str] = None
    tracking_state: Optional[str] = None
    order_number: Optional[str] = None
    order_date: Optional[str] = None
    location_id: Optional[str] = None
    shipping_method: Optional[str] = None

    def to_str(self, **kwargs) -> str:
        return pprint.pformat(self.model_dump(**kwargs))

    def to_json(self, **kwargs) -> str:
        return self.model_dump_json(**kwargs)

    def to_dict(self, **kwargs) -> Dict[str, Any]:
        return self.model_dump(**kwargs)

    @classmethod
    def from_json(cls, json_str: str, **kwargs) -> Optional[Self]:
        return cls.model_validate_json(json_str, **kwargs)

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]], **kwargs) -> Optional[Self]:
        return cls.model_validate(obj, **kwargs) if isinstance(obj, Dict) else None
