# coding: utf-8
#
# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.

from enum import Enum, unique


@unique
class TrackingSignatureRequirement(Enum):
    """
    The signature_requirement field serves the purpose of validating the service option type, specifically proof of delivery. By collecting the recipient's signature upon delivery, it ensures the package reaches the intended recipient and prevents disputes related to non-delivery or lost packages.</br>

    allowed enum values
    """

    SIGNATURE_REQUIRED = "signature_required"
    ADULT_SIGNATURE_REQUIRED = "adult_signature_required"
    INDIRECT_SIGNATURE_REQUIRED = "indirect_signature_required"
    NO_SIGNATURE_REQUIRED = "no_signature_required"
    NULL = "null"
