# coding: utf-8
#
# This code was auto generated by AfterShip SDK Generator.
# Do not edit the class manually.

from enum import Enum, unique


@unique
class TrackingLastMileSource(Enum):
    """
    The field indicates the source of last-mile carrier.

    allowed enum values
    """

    SYSTEM = "system"
    USER = "user"
